server:
  port: 11007

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp16260nz54g895j26o.mysql.rds.aliyuncs.com:3306/1007?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: test_account
    password: Test123456
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 86400
  jackson:
    time-zone: Asia/Shanghai
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/rainng_course

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rainng.coursesystem.model